monolog:
    channels: ['g2f_heylight_payment_plugin']
    handlers:
        g2fHeyLightPaymentPluginHandler:
            type: rotating_file
            path: "%kernel.logs_dir%/g2f_heylight_payment_plugin_%kernel.environment%.log"
            level: error
            channels: [ "g2f_heylight_payment_plugin" ]
